Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,12 +12,13 @@ jobs:
       - name: Assume AWS Role (Dev Account)
         id: assume-dev-role
         run: >
-          aws sts assume-role \
-            --role-arn arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/ECRProdAccessRole \
-            --role-session-name GitHubActions
-          echo "::set-output name=AWS_ACCESS_KEY_ID::$(echo ${{ steps.assume-dev-role.outputs.stdout }} | jq -r '.Credentials.AccessKeyId')"
-          echo "::set-output name=AWS_SECRET_ACCESS_KEY::$(echo ${{ steps.assume-dev-role.outputs.stdout }} | jq -r '.Credentials.SecretAccessKey')"
-          echo "::set-output name=AWS_SESSION_TOKEN::$(echo ${{ steps.assume-dev-role.outputs.stdout }} | jq -r '.Credentials.SessionToken')"
+          OUTPUT=$(aws sts assume-role \
+            --role-arn arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/ECRDevAccessRole \
+            --role-session-name GitHubActions) || echo "Failed to assume role"
+            
+          echo "::set-output name=AWS_ACCESS_KEY_ID::$(echo $OUTPUT | jq -r '.Credentials.AccessKeyId')"
+          echo "::set-output name=AWS_SECRET_ACCESS_KEY::$(echo $OUTPUT | jq -r '.Credentials.SecretAccessKey')"
+          echo "::set-output name=AWS_SESSION_TOKEN::$(echo $OUTPUT | jq -r '.Credentials.SessionToken')"
           
       - name: Login to Docker Hub
         run: >-
